 (cd "$(git rev-parse --show-toplevel)" && git apply --3way <<'EOF' 
diff --git a/dax/measures.dax b/dax/measures.dax
index 5b63eae24f261d514d9cee7fcda68df2838c895b..3382ca11202fc4fe9e942ba461f8d84544e20286 100644
--- a/dax/measures.dax
+++ b/dax/measures.dax
@@ -1 +1,128 @@
--- DAX measures will be generated by Codex
+-- =====================================
+-- プロジェクト一覧: DAX Measures
+-- =====================================
+
+-- 基本件数
+Total Projects =
+DISTINCTCOUNT(FactProject[ProjectID])
+
+In Progress Projects =
+CALCULATE(
+    [Total Projects],
+    KEEPFILTERS(FactProject[Status] = "In Progress")
+)
+
+Completed Projects =
+CALCULATE(
+    [Total Projects],
+    KEEPFILTERS(FactProject[Status] = "Completed")
+)
+
+High Risk Projects =
+CALCULATE(
+    [Total Projects],
+    KEEPFILTERS(FactProject[RiskLevel] = "High")
+)
+
+Delayed Projects =
+CALCULATE(
+    [Total Projects],
+    FILTER(
+        FactProject,
+        FactProject[Status] <> "Completed"
+            && FactProject[PlannedEndDate] < TODAY()
+    )
+)
+
+-- 金額
+Planned Cost =
+SUM(FactProject[PlannedCost])
+
+Actual Cost =
+SUM(FactProject[ActualCost])
+
+Cost Variance =
+[Actual Cost] - [Planned Cost]
+
+Cost Variance % =
+DIVIDE([Cost Variance], [Planned Cost], 0)
+
+Budget Burn Rate % =
+DIVIDE([Actual Cost], [Planned Cost], 0)
+
+-- 進捗
+Average Progress % =
+AVERAGE(FactProject[ProgressPct])
+
+Completion Rate % =
+DIVIDE([Completed Projects], [Total Projects], 0)
+
+-- 遅延
+Delay Days =
+VAR PlannedDate = MAX(FactProject[PlannedEndDate])
+VAR ActualOrToday = COALESCE(MAX(FactProject[EndDate]), TODAY())
+RETURN
+DATEDIFF(PlannedDate, ActualOrToday, DAY)
+
+Avg Delay Days =
+AVERAGEX(
+    VALUES(FactProject[ProjectID]),
+    [Delay Days]
+)
+
+On-time Completion Rate % =
+DIVIDE(
+    CALCULATE(
+        [Completed Projects],
+        FILTER(
+            FactProject,
+            FactProject[Status] = "Completed"
+                && FactProject[EndDate] <= FactProject[PlannedEndDate]
+        )
+    ),
+    [Completed Projects],
+    0
+)
+
+-- 条件付き書式（色コード返却）
+Progress Color =
+SWITCH(
+    TRUE(),
+    [Average Progress %] >= 0.8, "#2E7D32",
+    [Average Progress %] >= 0.5, "#F9A825",
+    "#C62828"
+)
+
+Cost Variance Color =
+VAR Planned = [Planned Cost]
+VAR Variance = [Cost Variance]
+RETURN
+SWITCH(
+    TRUE(),
+    Variance <= 0, "#2E7D32",
+    Variance <= Planned * 0.1, "#F9A825",
+    "#C62828"
+)
+
+Delay Color =
+VAR Days = [Delay Days]
+RETURN
+SWITCH(
+    TRUE(),
+    Days <= 0, "#2E7D32",
+    Days <= 14, "#F9A825",
+    "#C62828"
+)
+
+Risk Color =
+SWITCH(
+    SELECTEDVALUE(FactProject[RiskLevel], "Medium"),
+    "Low", "#2E7D32",
+    "Medium", "#F9A825",
+    "High", "#C62828",
+    "#F9A825"
+)
+
+-- タイトル
+Dashboard Title =
+"プロジェクト一覧 - " & SELECTEDVALUE(DimDate[Year], "全期間")
 
EOF
)
